FORMAT: 1A
HOST: https://localhost:8081/

# 成分管理API

## このドキュメントの見方
このドキュメントに定義されているAPIは下記の分類で構成されています。
- 原材料管理API
- 半完成品管理API
- 完成品管理API
- マスター管理API

## Headerについて
このAPIは認証トークンが必要です。各APIには次のようにヘッダにトークンを設定します。
```
Authorization: Bearer {token}
Content-Type: (application/json)
```

## Responseについて
Response BodyはJSONオブジェクトとして次の形式で戻ります。
```
単一データの場合
{
    "status" : "Success",
    "field1" : "データ１",
    "field2" : "データ２",
}
```
```
複数件の場合
{
    "status" : "Success" ,
    "records" : 2,
    "item": [
        {
            "field1" : "データ１１",
            "field2" : "データ１２",
        },
        {
            "field1":"データ２１",
            "field2":"データ２２",
        }
    ]
}
```

# Data Structures

## SemiProductItemDetail

+ itemId ( number , required ) - 半製品ID（内部キー）
+ materialKb ( boolean , required ) - 原材料区分（True: 原材料、False：仕込品）
+ foodId ( number , required ) - 原材料ID（内部キー）
+ preProductId ( number , required ) - 仕込品ID（内部キー）
+ foodNo (string , required ) - 番号（仕込品番号or原材料番号）
+ foodName ( string , required ) - 名称（仕込品名or原材料名）
+ mixingRatio ( number , required ) - 配合率
+ weight ( number , required ) - 重量
+ costPrice ( number , required ) - 原価
+ energy ( number ,required ) - エネルギー
+ protein ( number ,required ) - タンパク質
+ fat ( number ,required ) - 脂質
+ carbo ( number ,required ) - 炭水化物
+ sugar ( number ,required ) - 糖質　炭水化物総量から食物繊維量を引いた数値 
+ sodium ( number ,required ) - 食塩相当量

## SemiProductItemDetails (array[SemiProductItemDetail])

## SemiProductItem (object)

+ itemId ( number , required ) - 半製品ID（内部キー）
+ itemNo ( string , required ) - 半製品品番号
+ itemKind ( number , required )  - 半製品分類
+ itemName ( string , required ) - 半製品名
+ displayName ( string , required ) - 表示名
+ capacity ( number , required ) - 内容量
+ unit ( number , required ) - 単位（選択式）
+ infUnit ( number , required ) - （栄養成分表示）単位 0:gあたり 1:１個あたり
+ infVolume ( number , required ) - （栄養成分表示）g
+ infDisplay ( number , required ) - （栄養成分表示）表記 0:の目安です 1:推定値です 2:の日本食品成分表の計算による 3:のサンプル品分析による推定値
+ infEnergy ( number ,required ) - （栄養成分表示）エネルギー
+ infProtein ( number ,required ) - （栄養成分表示）タンパク質
+ infFat ( number ,required ) - （栄養成分表示）脂質
+ infCarbo ( number ,required ) - （栄養成分表示）炭水化物
+ infSugar ( number ,required ) - （栄養成分表示）糖質　炭水化物総量から食物繊維量を引いた数値 
+ infSodium ( number ,required ) - （栄養成分表示）食塩相当量
+ infLmtKind( number , required ) - (栄養成分表示)表記種別0:賞味期限、1:消費期限
+ infLmtDateFlag( boolean , required ) - (栄養成分表示)日付指定（True:する。False:しない）
+ infLmtDate (string , optional ) - （栄養成分表示）日付
+ infStorageMethod ( string , optional ) - （栄養成分表示）保存方法
+ infContamiFlag (boolean ,required ) - コンタミネーションフラグ（True:あり、False:なし）
+ infContamination ( string , optional) - （栄養成分表示）コンタミネーション内容
+ weightSum (number , required ) - 重量合計
+ costPriceSum ( number, required ) - 原価合計
+ detailCount ( number , required ) - 明細件数
+ placeOfOrigin (string ,optional ) - 原産地
+ purpose ( string , optional ) - 用途

## SemiProductItems (array[SemiProductItem])


## PreProductItemDetail

+ itemId ( number , required ) - 仕込品ID（内部キー）
+ foodId ( number , required ) - 原材料ID（内部キー）
+ composite_raw_materials_kb ( boolean , required ) - 複合原材料フラグ 0(False):通常 1(True):複合原材料(中間加工原料)
+ foodName ( string , required ) - 原材料名
+ mixingRatio ( number , required ) - 配合率
+ weight ( number , required ) - 重量
+ costPrice ( number , required ) - 原価
+ energy ( number ,required ) - エネルギー
+ protein ( number ,required ) - タンパク質
+ fat ( number ,required ) - 脂質
+ carbo ( number ,required ) - 炭水化物
+ sugar ( number ,required ) - 糖質　炭水化物総量から食物繊維量を引いた数値 
+ sodium ( number ,required ) - 食塩相当量

## PreProductItemDetails (array[PreProductItemDetail])


## PreProductItem (object)

+ itemId ( number , required ) - 仕込品ID（内部キー）
+ itemNo ( string , required ) - 仕込品番号
+ itemKind ( number , required )  - 仕込品分類
+ itemName ( string , required ) - 仕込品名
+ displayName ( string , required ) - 表示名
+ capacity ( number , required ) - 内容量
+ unit ( number , required ) - 単位（選択式）
+ infUnit ( number , required ) - （栄養成分表示）単位 0:gあたり 1:１個あたり
+ infVolume ( number , required ) - （栄養成分表示）g
+ infDisplay ( number , required ) - （栄養成分表示）表記 0:の目安です 1:推定値です 2:の日本食品成分表の計算による 3:のサンプル品分析による推定値
+ infEnergy ( number ,required ) - （栄養成分表示）エネルギー
+ infProtein ( number ,required ) - （栄養成分表示）タンパク質
+ infFat ( number ,required ) - （栄養成分表示）脂質
+ infCarbo ( number ,required ) - （栄養成分表示）炭水化物
+ infSugar ( number ,required ) - （栄養成分表示）糖質　炭水化物総量から食物繊維量を引いた数値 
+ infSodium ( number ,required ) - （栄養成分表示）食塩相当量
+ infLmtKind( number , required ) - （栄養成分表示）表記種別0:賞味期限、1:消費期限
+ infLmtDateFlag( boolean , required ) - （栄養成分表示）日付指定（True:する。False:しない）
+ infLmtDate (string , optional ) - （栄養成分表示）日付
+ infStorageMethod ( string , optional ) - （栄養成分表示）保存方法
+ infContamiFlag (boolean ,required ) - コンタミネーションフラグ（True:あり、False:なし）
+ infContamination ( string , optional) - （栄養成分表示）コンタミネーション内容
+ weightSum (number , required ) - 重量合計
+ costPriceSum ( number, required ) - 原価合計
+ detailCount ( number , required ) - 明細件数
+ placeOfOrigin ( string , optional ) - 原産地
+ purpose ( string , optional ) - 用途

## PreProductItems (array[PreProductItem])

## RawMaterial (object)

+ foodId (number , required) - 原材料ID（内部キー）
+ foodNo (string , required) - 原材料番号
+ originalFoodGroupId (number , optional ) - 参照元原材料ID
+ originalFoodNo (string , optional) - 参照元原材料番号
+ originalIntexNo (string , optional) - 参照元索引番号
+ foodName (string , required) - 原材料名
+ foodFukuBunrui (string , optional) - 副分類
+ foodRuiKubun (string , optional) - 類分類
+ foodDaiBunrui (string , optional) - 大分類
+ foodCyuBunrui (string , optional) - 中分類
+ foodSyoBunrui (string , optional) - 小分類
+ foodSaibun (string , optional) - 細分
+ originalFoodName (string , optional) - 参照元原材料名
+ categoryId (number , required) - 1:８訂成分データ、2:拡張成分データ、3:ユーザ定義成分データ
+ hashtag (string , optional) - ハッシュタグ
+ supplier_id (number , optional) - 仕入れ元ID
+ purchase_price (number , optional) - 仕入れ単価
+ volume_amount (number , optional) - 仕入れ容量(gかmlで入力) 
+ weight_or_capacity (number , optional) - 0:重さ(g) 1:容量(ml)
+ convertRatio (number , optional) - 重さ/容量 1:100g/100ml ......
+ composite_raw_materials_kb (boolean , required ) - 複合原材料フラグ false:通常 true:複合原材料(中間加工原料)
+ price_per_unit (number , optional) - 100グラム単価
+ maker_id (number , optional) - 製造元
+ saller_id (number , optional) - 販売元
+ composite_raw_itemlist (string , optional) - 原材料表記用の記載 ex.マヨネーズ（卵、食用植物油脂、醸造酢、香辛料、食塩、砂糖） 当該複合原材料の原材料が３種類以上ある場合は、当該複合原材料の原材料に占める重量の割合の高い順が３位以下であって、かつ、当該割合が５％未満である原材料については「その他」とまとめて表示することができます。 複合原材料の省略規定として 複合原材料の製品の原材料に占める重量の割合が５％未満であるとき。と、複合原材料の名称からその原材料が明らかなとき（ex.鶏唐揚げとかサバ味噌煮などの主要原材料が明示）　(ex.ミートボール、魚介エキス、植物性たんぱく加水分解物等の主要原材料を総称名称の場合)　(ロースハムやマヨネーズなどJAS規格、食品表示基準別表第３などで定義されている場合)　(その他一般に原材料が明らかである場合、ex.かまぼこ、がんもどき、ハンバーグ等)
+ display_name (string , optional) - 品目表示名
+ place_of_origin (string , optional) - 原産国名 （複合原材料の原料原産地表示について、生鮮原材料の原産地まで遡って表示する場合、複合原材料の原材料に占める重量割合が最も高い原材料（複合原材料の重量割合上位１位の原材料）の原産地の表示が必要です。） 
+ display_place_of_origin (string , optional) - 表示用原料原産地
+ revision_of_food_no (number , optional) - 同一foodNoでのリビジョン 0:-........
+ next_food_id (number , optional) - 次のfood_id
+ expire_date (string , optional) - 利用有効期限リミット
+ create_date (string , optional) - 登録日時
+ last_update_date (string , optional) - 更新日時
+ status (number , optional) - レコード状態 0:本登録 1:仮登録 2:新規利用不可
+ update_information (string , optional) - 更新履歴：ex 単価変更とか、成分変更とか容量変更などのメモを記載
+ refuse (number , optional) - 廃棄率(%)
+ refuse_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ enerc (number ,optional) - エネルギー(kJ)
+ enerc_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ enerc_kcal (number , optional) - エネルギー(kcal)
+ enerc_kcal_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ water (number , optional) - 水分(g)
+ water_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ protcaa (number , optional) - タンパク質 アミノ酸組成によるたんぱく質(g)
+ protcaa_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ prot (number , optional) - タンパク質(g)
+ prot_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ fatnlea (number , optional) - 脂肪酸のトリアシルグリセロール当量(g)
+ fatnlea_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ chole (number , optional) - コレステロール(mg)
+ chole_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ fat (number , optional) - 脂質(g)
+ fat_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ choavlm (number , optional) - 利用可能炭水化物：単糖当量(g)
+ choavlm_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ choavlm_mark (boolean , optional) - カロリー計算に炭水化物量（単糖当量）を用いたなら1それ以外は0
+ choavl (number , optional) - 利用可能炭水化物：質量計(g)
+ choavl_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ choavldf (number , optional) - 差引き法による利用可能炭水化物(g)
+ choavldf_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ choavldf_mark (boolean , optional) - カロリー計算に差引き法の利用可能炭水化物量を用いたなら1それ以外は0
+ fib (number , optional) - 植物繊維総量(g)
+ fib_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ polyl (number , optional) - 糖アルコール(g)
+ polyl_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ chocdf (number , optional) - 炭水化物(g)
+ chocdf_flag (number , optional) - フラグ(0:実測値, 1:推定値, 2:実測Tr, 3:推定Tr, 4:実測-, 5:推定-)
+ oa (number , optional) - 有機酸(g)
+ oa_flag (number , optional) - フラグ(0:実測値, 1:推定値, 2:実測Tr, 3:推定Tr, 4:実測-, 5:推定-)
+ ash (number , optional) - 灰分(g)
+ ash_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ na (number , optional) - ナトリウム(mg)
+ na_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ k (number , optional) - カリウム(mg)
+ k_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ ca (number , optional) - カルシウム(mg)
+ ca_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ mg (number , optional) - マグネシウム(mg)
+ mg_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ p (number , optional) - リン(mg)
+ p_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ fe (number , optional) - 鉄(mg)
+ fe_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ zn (number , optional) - 亜鉛(mg)
+ zn_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ cu (number , optional) - 銅(mg)
+ cu_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ mn (number , optional) - マンガン(mg)
+ mn_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ id (number , optional) - ヨウ素(μg)
+ id_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ se (number , optional) - セレン(μg)
+ se_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ cr (number , optional) - クロム(mg)
+ cr_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ mo (number , optional) - モリブデン(mg)
+ mo_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ ret (number , optional) - レチノール(μg)
+ ret_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ carta (number , optional) - αカロテン(μg)
+ carta_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ cartb (number , optional) - βカロテン(μg)
+ cartb_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ crypxb (number , optional) - βクリプトキサンチン(μg)
+ crypxb_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ cartbeq (number , optional) - βカロテン当量(μg)
+ cartbeq_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ vita_rae (number , optional) - レチノール活性当量(μg)
+ vita_rae_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ vitd (number , optional) - ビタミンD(μg)
+ vitd_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ tocpha (number , optional) - αトコフェロール(mg)
+ tocpha_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ tocphb (number , optional) - βトコフェロール(mg)
+ tocphb_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ tocphg (number , optional) - γトコフェロール(mg)
+ tocphg_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ tocphd (number , optional) - δトコフェロール(mg)
+ tocphd_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ vitk (number , optional) - ビタミンK(μg)
+ vitk_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ thia (number , optional) - ビタミンB1(mg)
+ thia_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ ribf (number , optional) - ビタミンB2(mg)
+ ribf_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ nia (number , optional) - ナイアシン(mg)
+ nia_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ niac (number , optional) - ナイアシン当量(mg)
+ niac_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ vitb6a (number , optional) - ビタミンB6(mg)
+ vitb6a_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ vitb12 (number , optional) - ビタミンB12(μg)
+ vitb12_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ fol (number , optional) - 葉酸(μg)
+ fol_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ pantac (number , optional) - パントテン酸(mg)
+ pantac_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ biot (number , optional) - ビオチン(μg)
+ biot_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ vitc (number , optional) - ビタミンC(mg)
+ vitc_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ alc (number , optional) - アルコール(エタノール)(g)
+ alc_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ nacl_eq (number , optional) - 食塩相当量(g)
+ nacl_eq_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ description (string , optional) - 説明
+ description_flag (number , optional) - 0:初期値, 1:参照値 2:実測値 3:変更値 
+ is_active (boolean , optional) - アクティブフラグ

## RawMaterials (array[RawMaterial])


## RawMaterialSupplier (object)

+ id (number , required) - ID（内部キー）
+ foodId (number, required) - 原材料ID（原材料を特定する内部キー）
+ supplierId (number, required) - 仕入元ID（仕入元を特定する内部キー）
+ supplierName (string , required) - 仕入元名
+ purchasePrice (number , required) - 仕入単価
+ volumeAmount (number , required) - 仕入容量（gかmlで入力）
+ weightOrCapacity (number , required) - 0:重さ（g）、1:容量（ml）
+ convertRation (number , required) - 重さ÷容量での変換レート、デフォルトは1.00
+ pricePerUnit (number , required) - 100g単価　デフォルト0
+ createDate (number , optional) - 作成日
+ lastUpdateDate (number , optional) - 更新日
+ isActive ( boolean , optional) -　アクティブフラグ　True:有効、False:無効

## RawMaterialSuppliers (array[RawMaterialSupplier])

## CommonListContent (object)

+ id (number , required) - ID（内部キー）
+ name (string , required) - 名称
+ no ( string , optional) - no（一般的に外部キーとして使用）
+ description ( string , optional ) - 概略

## CommonListContents (array[CommonListContent])

## MasterSupplier (object)

+ supplierId (number , required) - 仕入元ID（内部キー）
+ supplierName (string , required) - 仕入元名
+ contactInfo (string , optional) - 連絡先情報

## MasterSuppliers (array[MasterSupplier])

## MasterSaller (object)

+ sallerId (number , required ) - 販売元ID（内部キー）
+ sallerName ( string , required ) - 販売元名 
+ contactInfo (string , optional) - 連絡先情報

## MasterSallers (array[MasterSaller])

## MasterMaker (object)

+ makerId (number , required ) - 製造者（社）ID（内部キー）
+ makerName ( string , required ) - 製造者（社）名 
+ contactInfo (string , optional) - 連絡先情報

## MasterMakers (array[MasterMaker])

## SelectItem (object)

+ value (number , required ) - 選択値
+ label (string , required ) - 表示名

## SelectItems (array[SelectItem])

## 半完成品管理API [/apix/FoodSemiMaterial/]
半完成品に関わるAPIを定義します。

### 半完成品リスト取得
半完成品（JSON形式）を取得するメソッド。

+ Request
    + Headers
    ```
    Authorization: Bearer {token}
    Accept: text/plain
    ```
    
+ Response 200 (appication/json)

    + Attributes
        + status (string,required) - 成功時はSuccess、失敗時はFail
        + records (number,required) - 取得したデータ件数 レコード無しは0
        + item (SemiMaterials,optional) - 原材料データの配列
    

## 原材料管理API [/apix/FoodRawMaterial/]
原材料に関わるAPIを定義します。

### 原材料リスト取得 [GET /apix/FoodRawMaterial/GetDataX{?pattern_id}]
原材料リスト（JSON形式）を取得するメソッド。パラメータによりデータの種別を指定して取得することができる。

+ Request
    + Headers
    ```
    Authorization: Bearer {token}
    Accept: text/plain
    ```

+ Parameters
    + pattern_id (number,required) - 検索対象指定（1:８訂原材料一覧, 2:拡張原材料一覧, 3:ユーザ定義原材料一覧）

+ Response 200 (application/json)

    + Attributes 
        + status (string,required) - 成功時はSuccess、失敗時はFail
        + records (number,required) - 取得したデータ件数 レコード無しは0
        + item (RawMaterials,optional) - 原材料データの配列

    + Body
```json
{
  "status": "Success",
  "records": 1,
  "item": [
    {
      "foodId": 1,
      "foodNo": "1001",
      "originalFoodId": 1,
      "originalFoodGroupId": 1,
      "originalFoodNo": "1001",
      "originalIndexNo": "0001",
      "foodName": "アマランサス　玄穀",
      "foodFukuBunrui": "",
      "foodRuiKubun": "",
      "foodDaiBunrui": "アマランサス",
      "foodCyuBunrui": "",
      "foodSyoBunrui": "玄穀",
      "foodSaibun": "",
      "originalFoodName": "アマランサス　玄穀",
      "categoryId": 1,
      "hashtag": null,
      "supplierId": null,
      "purchasePrice": 0,
      "volumeAmount": 0,
      "weightOrCapacity": 0,
      "convertRatio": 1,
      "compositeRawMaterialsKb": 0,
      "pricePerUnit": 0,
      "makerId": null,
      "makerName": null,
      "sallerId": null,
      "sallerName": null,
      "compositeRawItemlist": null,
      "displayName": null,
      "placeOfOrigin": null,
      "displayPlaceOfOrigin": null,
      "revisionOfFoodNo": 0,
      "nextFoodId": null,
      "expireDate": null,
      "createDate": "2025-08-27T13:42:21.000+00:00",
      "lastUpdateDate": "2025-11-13T17:11:09.000+00:00",
      "status": 1,
      "updateInformation": null,
      "refuse": 0,
      "refuseFlag": 0,
      "enerc": 1452,
      "enercFlag": 0,
      "enercKcal": 343,
      "enercKcalFlag": 0,
      "water": 13.5,
      "waterFlag": 2,
      "protcaa": 11.3,
      "protcaaFlag": 1,
      "prot": 12.7,
      "protFlag": 2,
      "fatnlea": 5,
      "fatnleaFlag": 2,
      "chole": 0,
      "choleFlag": 1,
      "fat": 6,
      "fatFlag": 2,
      "choavlm": 63.5,
      "choavlmFlag": 2,
      "choavlmMark": null,
      "choavl": 57.8,
      "choavlFlag": 2,
      "choavldf": 59.9,
      "choavldfFlag": 2,
      "choavldfMark": null,
      "fib": 7.4,
      "fibFlag": 2,
      "polyl": 0,
      "polylFlag": 2,
      "chocdf": 64.9,
      "chocdfFlag": 2,
      "oa": 0,
      "oaFlag": 2,
      "ash": 2.9,
      "ashFlag": 2,
      "na": 1,
      "naFlag": 2,
      "k": 600,
      "ca": 160,
      "caFlag": 2,
      "mg": 270,
      "mgFlag": 2,
      "p": 540,
      "fe": 9.4,
      "feFlag": 2,
      "zn": 5.8,
      "znFlag": 2,
      "cu": 0.92,
      "cuFlag": 2,
      "mn": 6.14,
      "mnFlag": 2,
      "idd": 1,
      "iddFlag": 2,
      "se": 13,
      "seFlag": 2,
      "cr": 7,
      "crFlag": 2,
      "mo": 59,
      "moFlag": 2,
      "ret": 0,
      "retFlag": 1,
      "carta": 0,
      "cartaFlag": 2,
      "cartb": 2,
      "cartbFlag": 2,
      "crypxb": 0,
      "crypxbFlag": 2,
      "cartbeq": 2,
      "cartbeqFlag": 2,
      "vitaRae": -1,
      "vitaRaeFlag": 2,
      "vitd": 0,
      "vitdFlag": 1,
      "tocpha": 1.3,
      "tocphaFlag": 2,
      "tocphb": 2.3,
      "tocphbFlag": 2,
      "tocphg": 0.2,
      "tocphgFlag": 2,
      "tocphd": 0.7,
      "tocphdFlag": 2,
      "vitk": 0,
      "vitkFlag": 1,
      "thia": 0.04,
      "thiaFlag": 2,
      "ribf": 0.14,
      "ribfFlag": 2,
      "nia": 1,
      "niaFlag": 2,
      "niac": 3.8,
      "niacFlag": 1,
      "vitb6a": 0.58,
      "vitb6aFlag": 2,
      "vitb12": 0,
      "vitb12Flag": 1,
      "fol": 130,
      "folFlag": 2,
      "pantac": 1.69,
      "pantacFlag": 2,
      "biot": 16,
      "biotFlag": 2,
      "vitc": 0,
      "vitcFlag": 1,
      "alc": 0,
      "alcFlag": 2,
      "naclEq": 0,
      "naclEqFlag": 2,
      "description": ",",
      "descriptionFlag": "0",
      "isActive": true,
      "kflag": 2,
      "pflag": 2
    }
  ]
}
```            

### 原材料取得（原材料ID指定） [GET /apix/FoodRawMaterial/findById{?foodId}]
原材料データ（JSON形式）を取得するメソッド。原材料ID（内部キー）を指定して取得する。

+ Request

    + Headers
    ```
    Authorization: Bearer {token}
    Accept: text/plain
    ```
    
+ Parameters
    + foodId (number,required) - 原材料を特定する内部キー

+ Response 200 (application/json)

    + Attributes (RawMaterial)
        + status (string,required) - 成功時はSuccess、失敗時はFail

    + Body
```json
{
  "status": "Success",
  "foodId": 1,
  "foodNo": "1001",
  "originalFoodId": 1,
  "originalFoodGroupId": 1,
  "originalFoodNo": "1001",
  "originalIndexNo": "0001",
  "foodName": "アマランサス　玄穀",
  "foodFukuBunrui": "",
  "foodRuiKubun": "",
  "foodDaiBunrui": "アマランサス",
  "foodCyuBunrui": "",
  "foodSyoBunrui": "玄穀",
  "foodSaibun": "",
  "originalFoodName": "アマランサス　玄穀",
  "categoryId": 1,
  "hashtag": null,
  "supplierId": null,
  "purchasePrice": 0,
  "volumeAmount": 0,
  "weightOrCapacity": 0,
  "convertRatio": 1,
  "compositeRawMaterialsKb": 0,
  "pricePerUnit": 0,
  "makerId": null,
  "makerName": null,
  "sallerId": null,
  "sallerName": null,
  "compositeRawItemlist": null,
  "displayName": null,
  "placeOfOrigin": null,
  "displayPlaceOfOrigin": null,
  "revisionOfFoodNo": 0,
  "nextFoodId": null,
  "expireDate": null,
  "createDate": "2025-08-27T13:42:21.000+00:00",
  "lastUpdateDate": "2025-11-13T17:11:09.000+00:00",
  "status": 1,
  "updateInformation": null,
  "refuse": 0,
  "refuseFlag": 0,
  "enerc": 1452,
  "enercFlag": 0,
  "enercKcal": 343,
  "enercKcalFlag": 0,
  "water": 13.5,
  "waterFlag": 2,
  "protcaa": 11.3,
  "protcaaFlag": 1,
  "prot": 12.7,
  "protFlag": 2,
  "fatnlea": 5,
  "fatnleaFlag": 2,
  "chole": 0,
  "choleFlag": 1,
  "fat": 6,
  "fatFlag": 2,
  "choavlm": 63.5,
  "choavlmFlag": 2,
  "choavlmMark": null,
  "choavl": 57.8,
  "choavlFlag": 2,
  "choavldf": 59.9,
  "choavldfFlag": 2,
  "choavldfMark": null,
  "fib": 7.4,
  "fibFlag": 2,
  "polyl": 0,
  "polylFlag": 2,
  "chocdf": 64.9,
  "chocdfFlag": 2,
  "oa": 0,
  "oaFlag": 2,
  "ash": 2.9,
  "ashFlag": 2,
  "na": 1,
  "naFlag": 2,
  "k": 600,
  "ca": 160,
  "caFlag": 2,
  "mg": 270,
  "mgFlag": 2,
  "p": 540,
  "fe": 9.4,
  "feFlag": 2,
  "zn": 5.8,
  "znFlag": 2,
  "cu": 0.92,
  "cuFlag": 2,
  "mn": 6.14,
  "mnFlag": 2,
  "idd": 1,
  "iddFlag": 2,
  "se": 13,
  "seFlag": 2,
  "cr": 7,
  "crFlag": 2,
  "mo": 59,
  "moFlag": 2,
  "ret": 0,
  "retFlag": 1,
  "carta": 0,
  "cartaFlag": 2,
  "cartb": 2,
  "cartbFlag": 2,
  "crypxb": 0,
  "crypxbFlag": 2,
  "cartbeq": 2,
  "cartbeqFlag": 2,
  "vitaRae": -1,
  "vitaRaeFlag": 2,
  "vitd": 0,
  "vitdFlag": 1,
  "tocpha": 1.3,
  "tocphaFlag": 2,
  "tocphb": 2.3,
  "tocphbFlag": 2,
  "tocphg": 0.2,
  "tocphgFlag": 2,
  "tocphd": 0.7,
  "tocphdFlag": 2,
  "vitk": 0,
  "vitkFlag": 1,
  "thia": 0.04,
  "thiaFlag": 2,
  "ribf": 0.14,
  "ribfFlag": 2,
  "nia": 1,
  "niaFlag": 2,
  "niac": 3.8,
  "niacFlag": 1,
  "vitb6a": 0.58,
  "vitb6aFlag": 2,
  "vitb12": 0,
  "vitb12Flag": 1,
  "fol": 130,
  "folFlag": 2,
  "pantac": 1.69,
  "pantacFlag": 2,
  "biot": 16,
  "biotFlag": 2,
  "vitc": 0,
  "vitcFlag": 1,
  "alc": 0,
  "alcFlag": 2,
  "naclEq": 0,
  "naclEqFlag": 2,
  "description": ",",
  "descriptionFlag": "0",
  "isActive": true,
  "kflag": 2,
  "pflag": 2
}
```

### 原材料取得（原材料番号指定） [GET /apix/FoodRawMaterial/findByFoodNo{?foodNo}]
原材料データ（JSON形式）を取得するメソッド。原材料番号を指定して取得する。

+ Request

    + Headers
    ```
    Authorization: Bearer {token}
    Accept: text/plain
    ```

+ Parameters
    + foodNo (string, required) - 原材料を特定する原材料番号

+ Response 200 (application/json)

    + Attributes (RawMaterial)
        + status (string,required) - 成功時はSuccess、失敗時はFail

    + Body
```json
{
  "status": "Success",
  "foodId": 1,
  "foodNo": "1001",
  "originalFoodId": 1,
  "originalFoodGroupId": 1,
  "originalFoodNo": "1001",
  "originalIndexNo": "0001",
  "foodName": "アマランサス　玄穀",
  "foodFukuBunrui": "",
  "foodRuiKubun": "",
  "foodDaiBunrui": "アマランサス",
  "foodCyuBunrui": "",
  "foodSyoBunrui": "玄穀",
  "foodSaibun": "",
  "originalFoodName": "アマランサス　玄穀",
  "categoryId": 1,
  "hashtag": null,
  "supplierId": null,
  "purchasePrice": 0,
  "volumeAmount": 0,
  "weightOrCapacity": 0,
  "convertRatio": 1,
  "compositeRawMaterialsKb": 0,
  "pricePerUnit": 0,
  "makerId": null,
  "makerName": null,
  "sallerId": null,
  "sallerName": null,
  "compositeRawItemlist": null,
  "displayName": null,
  "placeOfOrigin": null,
  "displayPlaceOfOrigin": null,
  "revisionOfFoodNo": 0,
  "nextFoodId": null,
  "expireDate": null,
  "createDate": "2025-08-27T13:42:21.000+00:00",
  "lastUpdateDate": "2025-11-13T17:11:09.000+00:00",
  "status": 1,
  "updateInformation": null,
  "refuse": 0,
  "refuseFlag": 0,
  "enerc": 1452,
  "enercFlag": 0,
  "enercKcal": 343,
  "enercKcalFlag": 0,
  "water": 13.5,
  "waterFlag": 2,
  "protcaa": 11.3,
  "protcaaFlag": 1,
  "prot": 12.7,
  "protFlag": 2,
  "fatnlea": 5,
  "fatnleaFlag": 2,
  "chole": 0,
  "choleFlag": 1,
  "fat": 6,
  "fatFlag": 2,
  "choavlm": 63.5,
  "choavlmFlag": 2,
  "choavlmMark": null,
  "choavl": 57.8,
  "choavlFlag": 2,
  "choavldf": 59.9,
  "choavldfFlag": 2,
  "choavldfMark": null,
  "fib": 7.4,
  "fibFlag": 2,
  "polyl": 0,
  "polylFlag": 2,
  "chocdf": 64.9,
  "chocdfFlag": 2,
  "oa": 0,
  "oaFlag": 2,
  "ash": 2.9,
  "ashFlag": 2,
  "na": 1,
  "naFlag": 2,
  "k": 600,
  "ca": 160,
  "caFlag": 2,
  "mg": 270,
  "mgFlag": 2,
  "p": 540,
  "fe": 9.4,
  "feFlag": 2,
  "zn": 5.8,
  "znFlag": 2,
  "cu": 0.92,
  "cuFlag": 2,
  "mn": 6.14,
  "mnFlag": 2,
  "idd": 1,
  "iddFlag": 2,
  "se": 13,
  "seFlag": 2,
  "cr": 7,
  "crFlag": 2,
  "mo": 59,
  "moFlag": 2,
  "ret": 0,
  "retFlag": 1,
  "carta": 0,
  "cartaFlag": 2,
  "cartb": 2,
  "cartbFlag": 2,
  "crypxb": 0,
  "crypxbFlag": 2,
  "cartbeq": 2,
  "cartbeqFlag": 2,
  "vitaRae": -1,
  "vitaRaeFlag": 2,
  "vitd": 0,
  "vitdFlag": 1,
  "tocpha": 1.3,
  "tocphaFlag": 2,
  "tocphb": 2.3,
  "tocphbFlag": 2,
  "tocphg": 0.2,
  "tocphgFlag": 2,
  "tocphd": 0.7,
  "tocphdFlag": 2,
  "vitk": 0,
  "vitkFlag": 1,
  "thia": 0.04,
  "thiaFlag": 2,
  "ribf": 0.14,
  "ribfFlag": 2,
  "nia": 1,
  "niaFlag": 2,
  "niac": 3.8,
  "niacFlag": 1,
  "vitb6a": 0.58,
  "vitb6aFlag": 2,
  "vitb12": 0,
  "vitb12Flag": 1,
  "fol": 130,
  "folFlag": 2,
  "pantac": 1.69,
  "pantacFlag": 2,
  "biot": 16,
  "biotFlag": 2,
  "vitc": 0,
  "vitcFlag": 1,
  "alc": 0,
  "alcFlag": 2,
  "naclEq": 0,
  "naclEqFlag": 2,
  "description": ",",
  "descriptionFlag": "0",
  "isActive": true,
  "kflag": 2,
  "pflag": 2
}
```

### 原材料データ登録 [POST /apix/FoodRawMaterial/insert]
原材料データを新規登録する。原材料のデータを含むJSONオブジェクトを使用する。

+ Request (application/json)

    + Headers
    ```
    Authorization: Bearer {token}
    ```
    
    + Attributes (RawMaterial)

    + Body 

+ Response 200 (application/json)

    + Attributes (RawMaterial)
        + status (string,required) - 成功時はSuccess、失敗時はFail

    + Body 

### 原材料データ更新 [POST /apix/FoodRawMaterial/update]
原材料データを更新する。原材料のデータを含むJSONオブジェクトを使用する。

+ Request (application/json)

    + Headers
    ```
    Authorization: Bearer {token}
    ```
    
    + Attributes (RawMaterial)

    + Body 

+ Response 200 (application/json)

    + Attributes (RawMaterial)
        + status (string,required) - 成功時はSuccess、失敗時はFail

    + Body 

### 原材料削除（原材料ID指定） [GET /apix/FoodRawMaterial/delete{?foodId}]
原材料データを削除するメソッド。削除対象の原材料ID（内部キー）を指定する。

+ Request

    + Headers
    ```
    Authorization: Bearer {token}
    Accept: text/plain
    ```

+ Parameters

    + foodId (number,required) - 原材料を特定する内部キー

+ Response 200 (application/json)

    + Attributes
        + status (string,required) - 成功時はSuccess、失敗時はFail
        + id (number,required) - 削除対象の原材料ID

### 原材料仕入元情報取得 [GET /apix/FoodRawMaterialSupplier/findByFoodId{?foodId}]
原材料の仕入元として登録されている情報を取得する。

+ Request

    + Headers
    ```
    Authorization: Bearer {token}
    Accept: text/plain
    ```

+ Parameters

    + foodId (number,required) - 原材料を特定する内部キー

+ Response 200 (application/json)

    + Attributes
        + status (string,required) - 成功時はSuccess、失敗時はFail
        + records (number,required) - 取得したデータ件数 レコード無しは0
        + item (RawMaterialSuppliers,optional) - 対象原材料の仕入元リスト

### 原材料仕入元登録 [POST /apix/FoodRawMaterialSupplier/insert]
原材料の仕入元を追加登録

+ Request (application/json)

    + Headers
    ```
    Authorization: Bearer {token}
    ```
    
    + Attributes (RawMaterialSupplier)

    + Body 

+ Response 200 (application/json)

    + Attributes (RawMaterialSupplier)
        + status (string,required) - 成功時はSuccess、失敗時はFail

    + Body 

### 原材料仕入元データ更新 [POST /apix/FoodRawMaterialSupplier/update]
原材料の仕入元データを更新する。原材料のデータを含むJSONオブジェクトを使用する。

+ Request (application/json)

    + Headers
    ```
    Authorization: Bearer {token}
    ```
    
    + Attributes (RawMaterialSupplier)

    + Body 

+ Response 200 (application/json)

    + Attributes (RawMaterialSupplier)
        + status (string,required) - 成功時はSuccess、失敗時はFail

    + Body 

### 原材料仕入元削除（原材料ID指定） [GET /apix/FoodRawMaterialSupplier/delete{?id}]
原材料の仕入元データを削除するメソッド。削除対象の原材料仕入元ID（内部キー）を指定する。

+ Request

    + Headers
    ```
    Authorization: Bearer {token}
    Accept: text/plain
    ```

+ Parameters

    + id (number,required) - 原材料を特定する内部キー

+ Response 200 (application/json)

    + Attributes
        + status (string,required) - 成功時はSuccess、失敗時はFail
        + id (number,required) - 削除されたの原材料の仕入元ID


## マスター管理API [/apix/]
各種マスターデータの管理用APIを定義します。

### 仕入元一覧 [GET /apix/MasterSupplier/getData]
仕入元の一覧を取得する

+ Request
    + Headers
    ```
    Authorization: Bearer {token}
    Accept: text/plain
    ```

+ Response 200 (application/json)

    + Attributes
        + status (string,required) - 成功時はSuccess、失敗時はFail
        + records (number,required) - 取得したデータ件数 レコード無しは0
        + item (MasterSuppliers,optional) - 仕入元リスト

### 仕入元簡易一覧 [GET /apix/MasterSupplier/getList]
仕入元簡易一覧用データ取得

+ Request

    + Headers
    ```
    Authorization: Bearer {token}
    Accept: text/plain
    ```

+ Response 200 (application/json)

    + Attributes
        + status (string,required) - 成功時はSuccess、失敗時はFail
        + records (number,required) - 取得したデータ件数 レコード無しは0
        + item (CommonListContents,optional) - 簡易リスト
    

### 仕入元詳細 [GET /apix/MasterSupplier/findById{?id}]
仕入元情報データ取得

+ Request

    + Headers
    ```
    Authorization: Bearer {token}
    Accept: text/plain
    ```

+ Parameters
    + id (number, required) - 仕入元情報のID（内部キー）

+ Response 200 (application/json)

    + Attributes (MasterSupplier)
        + status (string,required) - 成功時はSuccess、失敗時はFail

### 仕入元登録 [POST /apix/MasterSupplier/insert]
仕入元情報を登録

+ Request (application/json)

    + Headers
    ```
    Authorization: Bearer {token}
    ```
    
    + Attributes (MasterSupplier)

    + Body 

+ Response 200 (application/json)

    + Attributes (MasterSupplier)
        + status (string,required) - 成功時はSuccess、失敗時はFail

    + Body 

### 仕入元更新 [POST /apix/MasterSupplier/update]
仕入元情報を更新
+ Request (application/json)

    + Headers
    ```
    Authorization: Bearer {token}
    ```
    
    + Attributes (MasterSupplier)

    + Body 

+ Response 200 (application/json)

    + Attributes (MasterSupplier)
        + status (string,required) - 成功時はSuccess、失敗時はFail

    + Body 

### 仕入元削除 [GET /apix/MasterSupplier/delete{?id}]
仕入元情報を削除する。

+ Request

    + Headers
    ```
    Authorization: Bearer {token}
    Accept: text/plain
    ```

+ Parameters

    + id (number,required) - 原材料を特定する内部キー

+ Response 200 (application/json)

    + Attributes
        + status (string,required) - 成功時はSuccess、失敗時はFail
        + id (number,required) - 削除された仕入元ID（内部キー）

### 仕入元選択一覧 [GET /apix/MasterSupplier/getSelect]
選択リスト等で使用するために仕入元名のラベルと、値の一覧を取得する。

+ Request

    + Headers
    ```
    Authorization: Bearer {token}
    Accept: text/plain
    ```

+ Response 200 (application/json)

    + Attributes
        + status (string,required) - 成功時はSuccess、失敗時はFail
        + records (number,required) - 取得したデータ件数 レコード無しは0
        + item (SelectItems,optional) - 簡易リスト



### 製造者（社）一覧 [GET /apix/MasterMaker/getData]
製造者（社）の一覧を取得する。

+ Request
    + Headers
    ```
    Authorization: Bearer {token}
    Accept: text/plain
    ```

+ Response 200 (application/json)

    + Attributes
        + status (string,required) - 成功時はSuccess、失敗時はFail
        + records (number,required) - 取得したデータ件数 レコード無しは0
        + item (MasterMakers,optional) - 製造者（社）リスト

### 製造者(社)簡易一覧 [GET /apix/MasterMaker/getList]
製造者（社）簡易一覧用データ取得

+ Request

    + Headers
    ```
    Authorization: Bearer {token}
    Accept: text/plain
    ```

+ Response  200 (application/json)

    + Attributes
        + status (string,required) - 成功時はSuccess、失敗時はFail
        + records (number,required) - 取得したデータ件数 レコード無しは0
        + item (CommonListContents,optional) - 簡易リスト

### 製造者(社)詳細 [GET /apix/MasterMaker/findById{?id}]
製造者（社）情報データ取得

+ Request

    + Headers
    ```
    Authorization: Bearer {token}
    Accept: text/plain
    ```

+ Parameters
    + id (number, required) - 製造者（社）情報のID（内部キー）

+ Response  200 (application/json)

    + Attributes (MasterMaker)
        + status (string,required) - 成功時はSuccess、失敗時はFail

### 製造者(社)登録 [POST /apix/MasterMaker/insert]
製造者（社）情報を登録

+ Request (application/json)

    + Headers
    ```
    Authorization: Bearer {token}
    ```
    
    + Attributes (MasterMaker)

    + Body 

+ Response 200 (application/json)

    + Attributes (MasterMaker)
        + status (string,required) - 成功時はSuccess、失敗時はFail

    + Body 

### 製造者(社)更新 [POST /apix/MasterMaker/update]
製造者（社）情報を更新
+ Request (application/json)

    + Headers
    ```
    Authorization: Bearer {token}
    ```
    
    + Attributes (MasterMaker)

    + Body 

+ Response 200 (application/json)

    + Attributes (MasterMaker)
        + status (string,required) - 成功時はSuccess、失敗時はFail

    + Body 

### 製造者(社)削除 [GET /apix/MasterMaker/delete{?id}]
製造者（社）情報を削除する。

+ Request

    + Headers
    ```
    Authorization: Bearer {token}
    Accept: text/plain
    ```

+ Parameters

    + id (number,required) - 原材料を特定する内部キー

+ Response 200 (application/json)

    + Attributes
        + status (string,required) - 成功時はSuccess、失敗時はFail
        + id (number,required) - 削除された製造者（社）ID（内部キー）

### 製造者(社)選択一覧 [GET /apix/MasterMaker/getSelect]
選択リスト等で使用するために製造者（社）名のラベルと、値の一覧を取得する。

+ Request

    + Headers
    ```
    Authorization: Bearer {token}
    Accept: text/plain
    ```

+ Response  200 (application/json)

    + Attributes
        + status (string,required) - 成功時はSuccess、失敗時はFail
        + records (number,required) - 取得したデータ件数 レコード無しは0
        + item (SelectItems,optional) - 簡易リスト

### 販売元一覧 [GET /apix/MasterSaller/getData]
販売元の一覧を取得する。

+ Request
    + Headers
    ```
    Authorization: Bearer {token}
    Accept: text/plain
    ```

+ Response  200 (application/json)

    + Attributes
        + status (string,required) - 成功時はSuccess、失敗時はFail
        + records (number,required) - 取得したデータ件数 レコード無しは0
        + item (MasterSallers,optional) - 販売元リスト

### 販売元簡易一覧 [GET /apix/MasterSaller/getList]
販売元簡易一覧用データ取得

+ Request

    + Headers
    ```
    Authorization: Bearer {token}
    Accept: text/plain
    ```

+ Response  200 (application/json)

    + Attributes
        + status (string,required) - 成功時はSuccess、失敗時はFail
        + records (number,required) - 取得したデータ件数 レコード無しは0
        + item (CommonListContents,optional) - 簡易リスト

### 販売元詳細 [GET /apix/MasterSaller/findById{?id}]
製造者（社）情報データ取得

+ Request

    + Headers
    ```
    Authorization: Bearer {token}
    Accept: text/plain
    ```

+ Parameters
    + id (number, required) - 販売元情報のID（内部キー）

+ Response 200 (application/json)

    + Attributes (MasterSaller)
        + status (string,required) - 成功時はSuccess、失敗時はFail

### 販売元登録 [POST /apix/MasterSaller/insert]
販売元情報を登録

+ Request (application/json)

    + Headers
    ```
    Authorization: Bearer {token}
    ```
    
    + Attributes (MasterSaller)

    + Body 

+ Response 200 (application/json)

    + Attributes (MasterSaller)
        + status (string,required) - 成功時はSuccess、失敗時はFail

    + Body 

### 販売元更新 [POST /apix/MasterSaller/update]
製造者（社）情報を更新
+ Request (application/json)

    + Headers
    ```
    Authorization: Bearer {token}
    ```
    
    + Attributes (MasterSaller)

    + Body 

+ Response 200 (application/json)

    + Attributes (MasterSaller)
        + status (string,required) - 成功時はSuccess、失敗時はFail

    + Body 

### 販売元削除 [GET /apix/MasterSaller/delete{?id}]
販売元情報を削除する。

+ Request

    + Headers
    ```
    Authorization: Bearer {token}
    Accept: text/plain
    ```

+ Parameters

    + id (number,required) - 原材料を特定する内部キー

+ Response 200 (application/json)

    + Attributes
        + status (string,required) - 成功時はSuccess、失敗時はFail
        + id (number,required) - 削除された販売元ID（内部キー）

### 販売元選択一覧 [GET /apix/MasterSaller/getSelect]
選択リスト等で使用するために販売元名のラベルと、値の一覧を取得する。

+ Request

    + Headers
    ```
    Authorization: Bearer {token}
    Accept: text/plain
    ```

+ Response 200 (application/json)

    + Attributes
        + status (string,required) - 成功時はSuccess、失敗時はFail
        + records (number,required) - 取得したデータ件数 レコード無しは0
        + item (SelectItems,optional) - 簡易リスト